name: Deploy Next.js site to Pages

on:
  push:
    branches: ["release/github-pages"]
  pull_request:
    branches: ["release/github-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    working-directory: pn_docs_next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'yarn'
          cache-dependency-path: pn_docs_next

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          static_site_generator: 'next'
          generator_config_file: 'pn_docs_next/next.config.mjs'

      - name: Dump Pages configuration
        run: |
          echo PAGES_BASE_URL:  ${{ steps.pages.outputs.base_url }}
          echo PAGES_ORIGIN:    ${{ steps.pages.outputs.origin }}
          echo PAGES_HOST:      ${{ steps.pages.outputs.host }}
          echo PAGES_BASE_PATH: ${{ steps.pages.outputs.base_path }}

      - name: Install dependencies
        run: yarn install

      - name: Build with Next.js
        run: yarn next build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: pn_docs_next/out

      - name: Some debugging
        run: |
          ls -a
          cd out
          ls

  deploy:
    environment:
      name: github-pages
      url: "https://projectnebulagh.github.io/pn_shop/pn_docs_next"
    runs-on: ubuntu-latest
    needs: build
    
    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
        
