name: Deploy Next.js site to Pages

on:
  push:
    branches: ["release/github-pages"]
  pull_request:
    branches: ["release/github-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    working-directory: pn_docs_next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'yarn'
          cache-dependency-path: pn_docs_next

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        run: yarn install

      - name: Build and start with Next.js
        run: |
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pn_docs_next/.next

  deploy:
    environment:
      name: github-pages
      url: "https://projectnebulagh.github.io/pn_shop/pn_docs_next"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
