name: Deploy Next.js site to Pages

on:
  push:
    branches: ["release/github-pages"]
  pull_request:
    branches: ["release/github-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    working-directory: pn_shop_next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: pn_shop_next

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ github.token }}
          static_site_generator: 'next'
          generator_config_file: 'pn_shop_next/next.config.mjs'

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages 
          path: pn_shop_next/out

  deploy:
    environment:
      name: github-pages
      url: "https://projectnebulagh.github.io/pn_shop"
    runs-on: ubuntu-latest
    needs: build
    
    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
        
        
